window._env_ = {
  JWT_SECRET: 'BestComunicationService',
  STORE_ENCRYPTION_KEY: 'a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6',
  HOST_NAME: 'http://localhost',
  NODE_ENV: 'dev',
  MONGO_MAX_POOL_SIZE: '500',
  MONGO_MIN_POOL_SIZE: '100',
  MONGO_INITDB_ROOT_USERNAME: 'root',
  MONGO_INITDB_ROOT_PASSWORD: 'secret',
  MONGO_URL:
    'mongodb://root:MareRosso23!@novu-staging.cluster-cyiypkxdqoiu.eu-central-1.docdb.amazonaws.com:27017/novu-db?directConnection=true&retryWrites=false',
  REDIS_HOST: 'novu-redis-stage-we7knu.serverless.euc1.cache.amazonaws.com',
  S3_LOCAL_STACK: 'http://s3:4566',
  S3_BUCKET_NAME: 'novu-local',
  S3_REGION: 'eu-central-1',
  AWS_ACCESS_KEY_ID: 'test',
  AWS_SECRET_ACCESS_KEY: 'test',
  API_PORT: '3000',
  REDIS_PORT: '6379',
  REDIS_CACHE_SERVICE_PORT: '6379',
  WS_PORT: '3002',
  REACT_APP_WS_URL: 'http://ws.local:3002',
  REACT_APP_API_URL: 'https://api.osirisecho.com',
  API_ROOT_URL: 'https://api.osirisecho.com',
  DISABLE_USER_REGISTRATION: 'false',
  FRONT_BASE_URL: 'http://web:4200',
  WIDGET_EMBED_PATH: 'http://api.local:4701/embed.umd.min.js',
  WIDGET_URL: 'http://api.local:4500',
  API_CONTEXT_PATH: 'api',
  NEW_RELIC_ENABLED: 'false',
};
